import 'package:meta/meta.dart';

class GraphicCardEntity {
  final partID,
      manufacture,
      chipSet,
      memory,
      memoryType,
      coreClock,
      boostClock,
      effectiveMemClock,
      interface,
      color,
      frameSync,
      length,
      tdp,
      dvi,
      hdmi,
      miniHdmi,
      displayPort,
      miniDisplayPort,
      expansionSlotWidth,
      cooling,
      externalPower,
      upVote;

  GraphicCardEntity(
      {@required this.partID,
      @required this.manufacture,
      @required this.chipSet,
      @required this.memory,
      @required this.memoryType,
      @required this.coreClock,
      @required this.boostClock,
      @required this.effectiveMemClock,
      @required this.interface,
      @required this.color,
      @required this.frameSync,
      @required this.length,
      @required this.tdp,
      @required this.dvi,
      @required this.hdmi,
      @required this.miniHdmi,
      @required this.displayPort,
      @required this.miniDisplayPort,
      @required this.expansionSlotWidth,
      @required this.cooling,
      @required this.externalPower,
      @required this.upVote});
}
