import 'package:equatable/equatable.dart';
import 'package:meta/meta.dart';

class Motherboard extends Equatable {
  final partID,
      manufacture,
      model,
      socket,
      formFactor,
      chipSet,
      memoryMax,
      memoryType,
      memorySlot,
      memorySpeed,
      multiGpu,
      pciEx16slot,
      pciEx8slot,
      pciEx4slot,
      pciEx1slot,
      m2slot,
      mSataSlot,
      onBoardInternet,
      sata6GB,
      onBoardVideo,
      usb20,
      usb32,
      supportECC,
      wirelessNetworking,
      raidSupport,
      upVote;

  Motherboard({
    @required this.partID,
    @required this.manufacture,
    @required this.model,
    @required this.socket,
    @required this.chipSet,
    @required this.memoryMax,
    @required this.memoryType,
    @required this.upVote,
    @required this.formFactor,
    @required this.memorySlot,
    @required this.memorySpeed,
    @required this.multiGpu,
    @required this.pciEx16slot,
    @required this.pciEx8slot,
    @required this.pciEx4slot,
    @required this.pciEx1slot,
    @required this.m2slot,
    @required this.mSataSlot,
    @required this.onBoardInternet,
    @required this.sata6GB,
    @required this.onBoardVideo,
    @required this.usb20,
    @required this.usb32,
    @required this.supportECC,
    @required this.wirelessNetworking,
    @required this.raidSupport,
  });

  @override
  List<Object> get props => [
        partID,
        manufacture,
        model,
        socket,
        formFactor,
        chipSet,
        memoryMax,
        memoryType,
        memorySlot,
        memorySpeed,
        multiGpu,
        pciEx16slot,
        pciEx8slot,
        pciEx4slot,
        pciEx1slot,
        m2slot,
        mSataSlot,
        onBoardInternet,
        sata6GB,
        onBoardVideo,
        usb20,
        usb32,
        supportECC,
        wirelessNetworking,
        raidSupport,
        upVote
      ];
}
